spring.application.name=wms-reader

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wms_reader
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson
spring.jackson.time-zone=Asia/Jakarta

# GeoServer request timeout settings
http.client.connect-timeout-ms=8000
http.client.read-timeout-ms=12000
